pipeline {
    agent any 

    environment{
        AWS_REGION = "us-west-2"
        IMAGE_NAME = "manojkrishnappa/md-genai:${GIT_COMMIT}"
    }

    stages{
        stage('Git-checkout'){
            steps{
                git branch: 'main', url:'https://github.com/ManojKRISHNAPPA/ProjectGenAI-WITHCICD.git'
            }
        }

        stage('Docker build'){
            steps{
                dir('Rag-Application'){
                    sh'''
                        printenv
                        docker build -t ${IMAGE_NAME} .    
                    '''
                }
            }
        }
    }   
}